accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

url_patterns = [
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
]

projects/urls.py
from django.urls import path

from projects.views import (
    ProjectListView,
    ProjectDetailView,
    ProjectCreateView,
)

urlpatterns = [
    path("", ProjectListView.as_view(), name="projects_list"),
    path("create/", ProjectCreateView.as_view(), name="create_project"),
    path("<int:pk>/", ProjectDetailView.as_view(), name="show_project"),
]

tracker/urls.py
from django.urls import path
from django.contrib import admin
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views

from projects.views import (
    # ProjectCreateView,
    # ProjectDeleteView,
    # ProjectUpdateView,
    # ProjectDetailView,
    ProjectListView,
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", RedirectView.as_view(), name="home"),
    path("projects/", ProjectListView.as_view(), name="projects_list"),
    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),
]

accounts/models.py
#from django.db import models

# Create your models here.

projects/models.py
from django.db import models


class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    members = models.ManyToManyField("auth.User", related_name="projects")

    def __str__(self):
        return self.name

tasks/models.py
# from tkinter import CASCADE
from django.db import models


class Task(models.Model):
    name = models.CharField(max_length=200)
    start_date = models.DateTimeField()
    due_date = models.DateTimeField()
    is_completed = models.BooleanField(default=False)
    project = models.ForeignKey(
        "projects.Project",
        related_name="tasks",
        on_delete=models.CASCADE,
    )
    assignee = models.ForeignKey(
        "auth.user",
        null=True,
        related_name="tasks",
        on_delete=models.SET_NULL,
    )

    def __str__(self):
        return self.name

accounts/views.py
# from django.shortcuts import render
from django.contrib.auth.models import User

# create_user method to create a new user
# account from their username/pw

user = User.objects.create_user("username", "password")

projects/views.py
# from msilib.schema import ListView
#from asyncio import tasks
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView


# from django.shortcuts import render
from projects.models import Project


class ProjectListView(ListView):
    model = Project
    template_name = "projects/list.html"


class ProjectDetailView(LoginRequiredMixin, DetailView):
    model = Project
    template_name = "projects/details.html"


class ProjectCreateView(LoginRequiredMixin, CreateView):
    model = Project
    template_name = "projects/create.html"
    fields = ["name", "description", "members"]
    success_url = reverse_lazy("projects_list")

tasks/views.py
# from django.shortcuts import render

# Create your views here.

projects/templates/projects/create.html
<!DOCTYPE html>
<html lang="en">

    <head>
        <title>Tracker</title>
    </head>

    <body>
        <main>
            <div>

            </div>
        </main>
    </body>


</html>

projects/templates/projects/details.html
<!-- Create a template to show the details
    of the project and a table of its tasks-->

<!DOCTYPE html>
<html lang="en">

    <!-- the "Is completed" column shows "yes" and "no"
     for the task is_completed status. -->

    <head>
        <title>Tracker</title>
    </head>

    <body>
        <main>
            <div>
                <h1>{{ project_name }}</h1>
                <p><!-- project description goes here --> </p>
                <h2>Tasks</h2>
                <!-- if django:tasks, then show table -->
                <!-- table has 5 columns: name assignee start date
                due date and is completed with rows for each task -->
                <!-- otherwise -->
                <!-- p tag with "Project has no tasks" -->
            </div>
        </main>
    </body>


</html>

projects/templates/projects/list.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Tracker</title>  
</head>
<body>
    <main>
        <div>
            <h1>My Projects</h1>
            {% if project_list|length >= 1 %}
            <table>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Number of Tasks</th>
                    </tr>
                </thead>
                <tbody>
                {% for Project in project_list %}
                    <tr>
                        <td>{{ Project }}</td><td>{{ Tasks|length }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            {% else %}
                <p>You are not assigned to any projects</p>
            {% endif %}
        </div>
    </main>  
</body> 
    
    
</html>  